[common]
exclude_remarks = ["(到期|剩余流量|时间|官网|产品)"]
clash_rule_base = "https://gist.githubusercontent.com/Crayon112/bab01b18613ff72324ac115a693cd68c/raw/clash.yaml"

[[custom_groups]]
name = "HK"
type = "url-test"
rule = ["港|HK"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "SG"
type = "url-test"
rule = ["新加坡|狮城|新|SG"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "TW"
type = "url-test"
rule = ["台|新北|彰化|TW"]
url = "http://www.gstatic.com/generate_204"
interval = 300


[[custom_groups]]
name = "JP`"
type = "url-test"
rule = ["日((?!用).)+|东京|大阪|埼玉|JP"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "US`"
type = "url-test"
rule = ["美|洛杉矶|硅谷|达拉斯|费利蒙|凤凰城|芝加哥|圣何塞|西雅图|圣克拉拉|US"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "Oversea"
type = "select"
rule = ["[]HK", "[]SG", "[]JP", "[]TW", "[]US", "DIRECT"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "China"
type = "select"
rule = ["[]DIRECT", "?i:CN|China|回国|中国|江苏|北京|上海|广州|深圳|杭州|常州|徐州|青岛|宁波|镇江|back", "[]Oversea"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "Steam"
type = "select"
rule = ["[]China", "[]HK", "[]SG","[]JP", "[]TW", "[]US", "DIRECT"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "Scholar"
type = "select"
rule = ["[]China", "[]HK", "[]SG","[]JP", "[]TW", "[]US", "DIRECT"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "Microsoft"
type = "select"
rule = ["[]China", "[]HK", "[]SG","[]JP", "[]TW", "[]US", "DIRECT"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "OneDrive"
type = "select"
rule = ["[]China", "[]HK", "[]SG","[]JP", "[]TW", "[]US", "DIRECT"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "Apple"
type = "select"
rule = ["[]China", "[]HK", "[]SG","[]JP", "[]TW", "[]US", "DIRECT"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "Telegram"
type = "select"
rule = ["[]China", "[]HK", "[]SG","[]JP", "[]TW", "[]US"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "Bilibili"
type = "select"
rule = ["[]China", "[]HK", "[]TW", "DIRECT"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "Emby"
type = "select"
rule = ["[]China", "[]HK", "[]SG","[]JP", "[]TW", "[]US", "DIRECT"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "YouTube"
type = "select"
rule = ["[]China", "[]HK", "[]SG","[]JP", "[]TW", "[]US", "DIRECT"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "StreamingSE"
type = "select"
rule = ["[]China", "[]HK", "[]SG","[]JP", "[]TW", "[]US", "DIRECT"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "Streaming"
type = "select"
rule = ["[]China", "[]HK", "[]SG","[]JP", "[]TW", "[]US", "DIRECT"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "Final"
type = "select"
rule = ["[]China", "[]Oversea", "[]SG","[]JP", "[]TW", "[]US", "[]HK", "[]DIRECT"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[ruleset]
enabled = true
overwrite_original_rules = true
update_ruleset_on_request = true

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/tindy2013/subconverter/master/base/rules/LocalAreaNetwork.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "Oversea"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Proxy/Proxy.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "Oversea"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Global.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "China"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Direct/Direct.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "Steam"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Steam/Steam.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "Scholar"
ruleset = "https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/Scholar/Scholar.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "Microsoft"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Microsoft/Microsoft.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "Apple"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Apple/Apple.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "OneDrive"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OneDrive/OneDrive.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "Telegram"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Telegram/Telegram.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "Bilibili"
ruleset = "https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Bilibili.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "Emby"
ruleset = "https://raw.githubusercontent.com/Tartarus2014/For-own-use/master/Ruleset/Emby/Emby.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "StreamingSE"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/StreamingMedia/StreamingSE.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "Streaming"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/StreamingMedia/Streaming.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "Streaming"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/StreamingMedia/Streaming.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "China"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/China.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "China"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/China.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "China"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/China.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "China"
ruleset = "[]GEOCP, CN"
interval = 86400

[[rulesets]]
group = "Final"
ruleset = "[]MATCH"
